name: cryptox
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  blur: ^3.0.0
  country_code_picker: ^2.0.2
  animation_wrappers: ^1.0.0
  flutter_phoenix: ^1.0.0
  flutter_bloc: ^7.0.1
  shared_preferences: ^2.0.6
  fl_chart: ^0.36.2
  k_chart: ^0.3.2
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/bottom_icons/
    - assets/app_icons/
    - assets/crypto_icons/
    - assets/social_icons/
    - assets/news/
    - assets/exchanges/
    - assets/coins/
    - assets/nft/

flutter_intl:
  enabled: false
  class_name: S
  main_locale: en
